CREATE TABLE qr_data
(
    id                     BIGINT AUTO_INCREMENT PRIMARY KEY,
    image_path             VARCHAR(255) NULL,
    data                   LONGTEXT NULL,
    vehicle_card           VARCHAR(100) NULL,
    qr_scanner             VARCHAR(100) NULL,
    factory                VARCHAR(255) NULL,
    supplier_name_btm      VARCHAR(255) NULL,
    supplier_name_htx      VARCHAR(255) NULL,
    product_code           VARCHAR(255) NULL,
    product_name           VARCHAR(255) NULL,
    lot_id                 VARCHAR(50) NULL,
    lot_id_detail          VARCHAR(50) NULL,
    lot_number             VARCHAR(255) NULL,
    driver_1               VARCHAR(255) NULL,
    driver_2               VARCHAR(255) NULL,
    driver_3               VARCHAR(255) NULL,
    citizen_id_1           VARCHAR(20) NULL,
    citizen_id_2           VARCHAR(20) NULL,
    citizen_id_3           VARCHAR(20) NULL,
    license_plate          VARCHAR(50) NULL,
    estimated_arrival_time VARCHAR(255) NULL,
    note                   TEXT,
    status_checkin         BOOLEAN  DEFAULT FALSE,
    status                 VARCHAR(255) NULL,
    is_send_ai             BOOLEAN  DEFAULT FALSE,
    updated_at             DATETIME DEFAULT CURRENT_TIMESTAMP,
    created_at             DATETIME DEFAULT CURRENT_TIMESTAMP
);